Corrected tac_plus.conf file so that the tac_plus server starts up properly
It was logging out this error:

expecting 'protocol' but found '{' on line 8
Error: expecting 'protocol' but found '{' on line 8